name: 'Rerun Code Owners'

on:
  pull_request_review:
    types: [submitted, dismissed]

permissions: {}

jobs:
  rerun-codeowners:
    name: 'Rerun Codeowners Plus'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
      checks: read
    steps:
      - name: 'Rerun Checks'
        uses: shqear93/rerun-checks@cafa5c1c11c880f9b23e6a73ad8628483fdae798  # @v3
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          check-names: 'Run Codeowners Plus'
